# Generated by Django 3.1.3 on 2024-02-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240203_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='text_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_post',
        ),
    ]
