# Generated by Django 3.1.3 on 2024-02-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240203_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_like',
        ),
    ]
