# Generated by Django 3.1.3 on 2024-02-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_savedpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedpost',
            old_name='post',
            new_name='Post',
        ),
    ]
