# Generated by Django 5.0.1 on 2024-01-30 16:58

import user.manger
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.manger.customUserManager()),
            ],
        ),
    ]
